### ISSUE TITLE
JSON API Data rendered ignoring Jackson Config (e.g. date format...)

### ISSUE THREAD

**Issue by CalamarBicefalo** [toedter/spring-hateoas-jsonapi#18]
When trying to serialize a payload containing java 8 date/time types, spring-hateoas-jsonapi renders those without using the appropriate jackson modules and configuration.

Even when registering a bean that is then picked by Spring HATEOAS, we found out, internally, spring-hateoas-jsonapi, instantiates a vanilla object mapper dismissing any configuration provided. This prevents spring-hateoas-jsonapi from rendering java 8 dates and times appropriately (and fundamentally any other modules or configuration users may need).

The offending code is https://github.com/toedter/spring-hateoas-jsonapi/blob/bb1e3217b177f76e0d8fd8643ea22a86549417b4/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiData.java#L129-L131

When this code gets called, our POJO, which looks like this:

```kotlin
class APojoWithDates(
        val timestamp: Instant,
)
```

gets transformed into a java map like this:
```
{ timestamp={nano=63855000, epochSecond=1603291790} }
```

which of course won't be rendered properly down the line regardless of the root object mapper config as the class type has been lost.

Are we missing anything? Shouldn't that ObjectMapper be the root one with the user provided config?

Thanks!

**Comment by toedter** [comment]
Thanks for pointing this out. I will try to recreate this behavior with a test and then think about a solution. I will write some tests for your use case and will investigate how to configure the object mapper used in https://github.com/toedter/spring-hateoas-jsonapi/blob/bb1e3217b177f76e0d8fd8643ea22a86549417b4/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiData.java#L129-L131

**Comment by toedter** [comment]
Fixed it in the current snapshot, to modify the Jackson object mapper config, you could do something like

```
    @Configuration
    @WebAppConfiguration
    @EnableWebMvc
    @EnableHypermediaSupport(type = HAL)
    static class YourConfig {
        @Bean
        JsonApiMediaTypeConfiguration jsonApiMediaTypeConfiguration(ObjectProvider<JsonApiConfiguration> configuration,
                                                                    AutowireCapableBeanFactory beanFactory) {
            return new JsonApiMediaTypeConfiguration(configuration, beanFactory) {
                @Override
                ObjectMapper configureObjectMapper(ObjectMapper mapper, JsonApiConfiguration configuration) {
                    ObjectMapper objectMapper = super.configureObjectMapper(mapper, configuration);

                    objectMapper.registerModule(new JavaTimeModule());
                    objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
                    return objectMapper;
                }
            };
        }
    }
```

**Comment by CalamarBicefalo** [comment]
Thank you very much @toedter for such a prompt turn around!

I tried that, but it seems maybe you forgot to make `super.configureObjectMapper(mapper, configuration)` public? At the moment it is package private and I cannot really call the super method... Perhaps your test is in the same package?

**Comment by CalamarBicefalo** [comment]
I went with the method that is public instead, which also mutates the object mapper anyway.

Seems more reasonable as the JsonApiConfiguration is not used anyway.

```kotlin
@Bean
    fun jsonApiMediaTypeConfiguration(configuration: ObjectProvider<JsonApiConfiguration>,
                                      beanFactory: AutowireCapableBeanFactory): JsonApiMediaTypeConfiguration? {
        return object : JsonApiMediaTypeConfiguration(configuration, beanFactory) {
            override fun configureObjectMapper(mapper: ObjectMapper): ObjectMapper {
                val objectMapper: ObjectMapper = super.configureObjectMapper(mapper)
                objectMapper.registerModule(JavaTimeModule())
                objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
                return objectMapper
            }
        }
    }
```

**Comment by toedter** [comment]
You are right, using super.configureObjectMapper(mapper) is better. The Spring HATEOAS team is thinking of providing a more generic solution, see https://github.com/spring-projects/spring-hateoas/issues/1382

**Comment by toedter** [comment]
Now it is even easier, I implemented Greg's suggestion (in the current snapshot) and you can handle ObjectMapper configuration within your JsonApiConfiguration, like

```Java
        @Bean
        JsonApiConfiguration jsonApiConfiguration() {
            return new JsonApiConfiguration()
                    .withObjectMapperCustomizer(objectMapper -> {
                        objectMapper.registerModule(new JavaTimeModule());
                        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
                    });
        }

```
